import { deriveTitle } from "@/lib/format";
import type { MapPoint, Property } from "@/lib/types";

// Adapts a slim map point to the Property shape PropertiesMap renders in popups.
export function mapPointToProperty(pt: MapPoint): Property {
  return {
    id: pt.id,
    propertyType: pt.propertyType,
    uf: pt.uf,
    city: pt.city,
    neighborhood: pt.neighborhood,
    rawAddress: null,
    area: pt.area,
    bedrooms: pt.bedrooms,
    parkingSpots: pt.parkingSpots,
    yearBuilt: null,
    occupancyStatus: pt.occupancyStatus,
    condoPaymentRule: null,
    taxPaymentRule: null,
    title: deriveTitle(pt.propertyType, pt.bedrooms, pt.neighborhood),
    description: null,
    image: null,
    appraisedValue: null,
    saleValue: pt.saleValue,
    discount: pt.discount,
    modality: pt.modality,
    auctionDate: pt.auctionDate,
    link: null,
    inactive: false,
    acceptsFinancing: false,
    acceptsFgts: false,
    scores: {
      flip: null,
      liquidity: null,
      airbnb: null,
      student: null,
      family: null,
      commercial: null,
      convenience: null,
      investment: pt.investment,
    },
    profile: null,
    profileScore: null,
    clusterId: null,
    clusterLabel: null,
    h3: null,
    lat: pt.lat,
    lon: pt.lon,
    visualScore: null,
    visualNote: null,
    visualAge: null,
    priceRank: null,
    sizeRank: null,
    centerProximity: null,
    nearestPoi: {},
  };
}
